import { UserModel } from '@/models/user';
import { ProductModel } from '@/models/product';
import { OrderModel } from '@/models/order';
import { CustomerModel } from '@/models/customer';
import { DailyMetrics, BusinessHealthMetrics } from '@/models/analytics';

export const mockCurrentUser: UserModel = {
  id: 'usr_001',
  email: 'rajesh.owner@kiranaking.com',
  displayName: 'Rajesh Sharma',
  role: 'BUSINESS_OWNER',
  storeId: 'str_101',
  businessName: 'Kirana King Superstore',
  phone: '+91 98765 43210',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
  createdAt: '2026-01-15T09:00:00.000Z',
};

export const mockDailyMetrics: DailyMetrics = {
  totalRevenue: 28450,
  revenueChangePercent: 12.4,
  orderCount: 42,
  orderCountChangePercent: 8.5,
  averageOrderValue: 677.38,
  lowStockItemsCount: 4,
  totalCustomers: 184,
};

export const mockProducts: ProductModel[] = [
  {
    id: 'prod_1',
    name: 'India Gate Basmati Rice 5kg',
    sku: 'IG-BAS-05',
    barcode: '8901234567890',
    category: 'Groceries',
    costPrice: 420,
    sellingPrice: 510,
    stockQuantity: 28,
    minStockThreshold: 10,
    unit: 'bag',
    description: 'Premium aged long-grain basmati rice',
    updatedAt: '2026-09-29T14:30:00Z',
  },
  {
    id: 'prod_2',
    name: 'Tata Salt Vacuum Evaporated 1kg',
    sku: 'TT-SLT-01',
    barcode: '8901234567891',
    category: 'Groceries',
    costPrice: 22,
    sellingPrice: 28,
    stockQuantity: 65,
    minStockThreshold: 20,
    unit: 'pack',
    description: 'Desh Ka Namak with iodine enrichment',
    updatedAt: '2026-09-28T10:15:00Z',
  },
  {
    id: 'prod_3',
    name: 'Aashirvaad Superior MP Sharbati Atta 10kg',
    sku: 'ASH-ATT-10',
    barcode: '8901234567892',
    category: 'Groceries',
    costPrice: 430,
    sellingPrice: 495,
    stockQuantity: 4,
    minStockThreshold: 8,
    unit: 'bag',
    description: '100% pure whole wheat grain flour',
    updatedAt: '2026-09-30T08:00:00Z',
  },
  {
    id: 'prod_4',
    name: 'Fortune Sunlite Refined Sunflower Oil 1L',
    sku: 'FT-SUN-01',
    barcode: '8901234567893',
    category: 'Groceries',
    costPrice: 125,
    sellingPrice: 145,
    stockQuantity: 18,
    minStockThreshold: 12,
    unit: 'pouch',
    description: 'Light and healthy refined sunflower oil',
    updatedAt: '2026-09-29T16:20:00Z',
  },
  {
    id: 'prod_5',
    name: 'Amul Butter Pasteurised 500g',
    sku: 'AML-BUT-50',
    barcode: '8901234567894',
    category: 'Groceries',
    costPrice: 240,
    sellingPrice: 275,
    stockQuantity: 2,
    minStockThreshold: 6,
    unit: 'block',
    description: 'Utterly butterly delicious creamy table butter',
    updatedAt: '2026-09-30T07:45:00Z',
  },
  {
    id: 'prod_6',
    name: 'Surf Excel Quick Wash Detergent Powder 1kg',
    sku: 'SRF-EXC-01',
    barcode: '8901234567895',
    category: 'FMCG',
    costPrice: 130,
    sellingPrice: 155,
    stockQuantity: 32,
    minStockThreshold: 15,
    unit: 'pack',
    description: 'Faster stain removal technology',
    updatedAt: '2026-09-27T11:00:00Z',
  },
  {
    id: 'prod_7',
    name: 'Dettol Original Bathing Soap (Pack of 4)',
    sku: 'DTL-SOP-04',
    barcode: '8901234567896',
    category: 'Personal Care',
    costPrice: 160,
    sellingPrice: 199,
    stockQuantity: 0,
    minStockThreshold: 10,
    unit: 'pack',
    description: 'Germ protection formula with classic fragrance',
    updatedAt: '2026-09-30T09:10:00Z',
  },
];

export const mockOrders: OrderModel[] = [
  {
    id: 'ord_101',
    orderNumber: 'ORD-2026-0042',
    customerName: 'Sunita Verma',
    customerId: 'cust_1',
    items: [
      { productId: 'prod_1', productName: 'India Gate Basmati Rice 5kg', quantity: 1, unitPrice: 510, subtotal: 510 },
      { productId: 'prod_2', productName: 'Tata Salt Vacuum Evaporated 1kg', quantity: 2, unitPrice: 28, subtotal: 56 },
    ],
    totalAmount: 566,
    paymentMethod: 'UPI',
    status: 'COMPLETED',
    createdAt: '2026-09-30T10:45:00Z',
  },
  {
    id: 'ord_102',
    orderNumber: 'ORD-2026-0041',
    customerName: 'Amit Patel',
    customerId: 'cust_2',
    items: [
      { productId: 'prod_3', productName: 'Aashirvaad Atta 10kg', quantity: 1, unitPrice: 495, subtotal: 495 },
      { productId: 'prod_4', productName: 'Fortune Sunflower Oil 1L', quantity: 2, unitPrice: 145, subtotal: 290 },
      { productId: 'prod_5', productName: 'Amul Butter 500g', quantity: 1, unitPrice: 275, subtotal: 275 },
    ],
    totalAmount: 1060,
    paymentMethod: 'CASH',
    status: 'COMPLETED',
    createdAt: '2026-09-30T10:15:00Z',
  },
  {
    id: 'ord_103',
    orderNumber: 'ORD-2026-0040',
    customerName: 'Priya Nair',
    customerId: 'cust_3',
    items: [
      { productId: 'prod_6', productName: 'Surf Excel Detergent Powder 1kg', quantity: 2, unitPrice: 155, subtotal: 310 },
    ],
    totalAmount: 310,
    paymentMethod: 'CARD',
    status: 'PENDING',
    createdAt: '2026-09-30T09:50:00Z',
  },
  {
    id: 'ord_104',
    orderNumber: 'ORD-2026-0039',
    customerName: 'Ramesh Gupta',
    customerId: 'cust_4',
    items: [
      { productId: 'prod_1', productName: 'India Gate Basmati Rice 5kg', quantity: 2, unitPrice: 510, subtotal: 1020 },
    ],
    totalAmount: 1020,
    paymentMethod: 'CREDIT',
    status: 'COMPLETED',
    createdAt: '2026-09-30T09:20:00Z',
  },
];

export const mockCustomers: CustomerModel[] = [
  {
    id: 'cust_1',
    name: 'Sunita Verma',
    phone: '+91 98201 12345',
    email: 'sunita.v@gmail.com',
    totalPurchases: 14850,
    outstandingCredit: 0,
    lastVisitDate: '2026-09-30',
    loyaltyPoints: 340,
    address: 'B-402, Shanti Heights, Main Road',
  },
  {
    id: 'cust_2',
    name: 'Amit Patel',
    phone: '+91 97123 45678',
    email: 'amit.patel@yahoo.com',
    totalPurchases: 22400,
    outstandingCredit: 450,
    lastVisitDate: '2026-09-30',
    loyaltyPoints: 520,
    address: '12, Gokul Society, Sector 4',
  },
  {
    id: 'cust_3',
    name: 'Priya Nair',
    phone: '+91 99345 67890',
    email: 'priya.nair@hotmail.com',
    totalPurchases: 8900,
    outstandingCredit: 0,
    lastVisitDate: '2026-09-30',
    loyaltyPoints: 180,
    address: 'Flat 101, Green Acres',
  },
  {
    id: 'cust_4',
    name: 'Ramesh Gupta',
    phone: '+91 94567 89012',
    email: 'ramesh.gupta@gmail.com',
    totalPurchases: 31200,
    outstandingCredit: 1850,
    lastVisitDate: '2026-09-29',
    loyaltyPoints: 890,
    address: 'Shop 5, Market Yard',
  },
];

export const mockBusinessHealth: BusinessHealthMetrics = {
  overallScore: 84,
  profitabilityScore: 88,
  inventoryEfficiencyScore: 78,
  customerRetentionScore: 92,
  cashFlowScore: 80,
  insights: [
    'Gross margins on Groceries have increased by 3.2% this month.',
    'Customer repeat visit rate is strong at 68% over a 30-day window.',
    'Stock turnover for FMCG is healthy, but 4 staple grocery items require reordering.',
  ],
  recommendations: [
    'Restock Aashirvaad Atta and Amul Butter before the weekend rush.',
    'Follow up on ₹2,300 in pending khata/credit balances from 2 customers.',
    'Create a bundle offer for Basmati Rice and Sunflower Oil to raise average basket size.',
  ],
};
